version: '3.8'

services:
  teno-bot:
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      DEEPGRAM: ${DEEPGRAM}
      TOKEN: ${TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: ${DATABASE_URL}
      AZURE_SPEECH_REGION: ${AZURE_SPEECH_REGION}
    env_file:
      - .env
  teno-dashboard:
    ports:
      - 80:3000
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
    restart: unless-stopped
    environment:
      TOKEN: ${TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: ${DATABASE_URL}
      DASHBOARD_SECRET: ${DASHBOARD_SECRET}
      DASHBOARD_PROTOCOL: ${DASHBOARD_PROTOCOL}
      DASHBOARD_HOST: ${DASHBOARD_HOST}
      DASHBOARD_PORT: ${DASHBOARD_PORT}
      DASHBOARD_URL: ${DASHBOARD_URL}
    env_file:
      - .env
