version: '3.8'

services:
  teno-bot:
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
    restart: unless-stopped
    stop_grace_period: 30s
    environment:
      DEEPGRAM: ${DEEPGRAM}
      TOKEN: ${TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY}
      REDIS_URL: ${REDIS_URL}
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
